spring:
  application:
    name: event-validator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
    producer:
      acks: all
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        enable.idempotence: true
        max.block.ms: 5000
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000

validator:
  schema-registry:
    url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
